### ISSUE TITLE
Random number generator is biased.

### ISSUE THREAD

**Issue by paulhandy** [iotaledger-archive/mam.client.js#12]
Kindly, @puellavulnerata combed through the code as reported here:
https://twitter.com/puellavulnerata/status/1013906986717581313
and found a significant error in the key generating function:
https://github.com/iotaledger/mam.client.js/blob/master/src/index.js#L279
This shows a biased random number generator. [A-Z9] is an character set of length 27; this calls for, i,e., 81 bytes to be generated for an 81-tryte seed, and modulo 27 each byte to generate the seed. 255 % 27 leaves a bias toward the first 13 characters of the [A-Z9] sequence.
A rather good suggestion for generating random numbers and why the random number generator here, in tweet form, can be found here:
https://twitter.com/colmmacc/status/1012721284092973056
I would suggest to either remove the key generation function, as I don't think it's necessary to provide such in the context, or to modify it according to @colmmacc's suggestion.

**Comment by l3wi** [comment]
@paulhandy Thanks for copying this across. 

@puellavulnerata thanks for bringing this to our attention! Please see the PR fixing the issue. 

If you have any further suggestions or find any other bugs please let us know here on Github. However, if you prefer to use twitter for these types of things you can at me at @lewisfreiberg
