### ISSUE TITLE
encryption.js is vestigial, should be removed

### ISSUE THREAD

**Issue by paulhandy** [iotaledger-archive/mam.client.js#15]
https://github.com/iotaledger/mam.client.js/blob/master/src/encryption.js contains mostly vestigial code from before the first version of MAM. I'd suggest removing this, and replacing uses in index.js wrapper to Encryption.hash with functions from the upstream repository.

**Comment by sobolev-alexey** [comment]
According to @chrisdukakis, 
> replacing with other hash function won't work with existing bindings.
> because it breaks unmasking and authentication compatibility
> recipient won't be able to unmask and authenticate, unless rust code is changed.

**Comment by chrisdukakis** [comment]
I actually agree with Paul. His suggestion is not about using other hash algo than Curl-P. I don't really know where hash function should be fetched from. Is it part of rust bindings?

**Comment by sobolev-alexey** [comment]
@chrisdukakis this function is still in use 
https://github.com/iotaledger/mam.client.js/blob/master/src/encryption.js#L23

**Comment by obany** [comment]
I have reduced the code to the bare minimum with this PR https://github.com/iotaledger/mam.client.js/pull/49/commits/33311617c51323aed9bae7769b16870e6e07f3fd
