### ISSUE TITLE
Chrome browser compatibility issues with latest release

### ISSUE THREAD

**Issue by Core-pl** [iotaledger-archive/mam.client.js#29]
**Error message:**
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21

**Steps to reproduce:**
1. Adapt example from fetchSync.js to run it in browser (file attached)
2. Run script in Chrome, using latest release (21 nov 2018)
3. Error is thrown when script fetches from MAM

**My findings so far**
- In Firefox it works correct
- Does not matter if mam.web..js or mam.web.min.js is used
- Old releases (ones that uses IOTA library for init) worked correctly in chrome
- Messages published in Firefox can be read in Chrome (publish in Firefox, save root, fetch in Chrome)

[mam_test.zip](https://github.com/iotaledger/mam.client.js/files/2612708/mam_test.zip)

**Comment by allemanfredi** [comment]
I have the same issue!

**Comment by allemanfredi** [comment]
Hey  @Core-pl !!!  I found that if i use 'https://testnet140.tangle.works'  it works!!! do you know why?

**Comment by sobolev-alexey** [comment]
Hey,
there were some issues with Chrome like the one you reported above. We fixed them in the latest version.

**Comment by Core-pl** [comment]
Sounds great. I will test new library over the next few days across different platforms (windows, android, macOS).

**Comment by Core-pl** [comment]
Hi @sobolev-alexey , I have checked several browsers with the latest MAM release (as of 11 Feb 2019). 
Default web build passed with all modern browsers on multiple platforms, only outdated browsers have failed. Many thanks for updating!

I have a proposition to increase adoption of MAM across web developers. It would be great to publish web libraries builds in /lib folder, so developers can start using them instantly, rather than setting up infrastructure (linux, node, yarn). mam.web.js libraries were published in the past and these helped me a lot to get started.


**Current MAM library compatibility with browsers (default build):** 

- **WINDOWS 10:**
  - Firefox Quantum 65.0 : **PASSED**
   - Chrome 72.0.3626.96 : **PASSED**
  - Edge 42.17134.1.0 : **PASSED**
  - Internet Explorer 11.523.17134.0 : **FAILED** 👎 (that's outdated browser)
- **MACOS HIGH SIERRA 10.13.6**
  - Safari 12.0.3 (13606.4.5.3.1) : **PASSED**
  - Chrome 72.0.3626.96 : **PASSED**
- **ANDROID 4.4**
  - Chrome 72.0.3626.96 : **PASSED**
  - Firefox 65.0 : **PASSED**
  - Samsung Internet 1.0 (Chromium 18) : **FAILED** 👎 (that's outdated browser)
- **IOS 12.1.4**
  - Safari 12.0.3 (13606.4.5.3.1) : **PASSED**
  - Chrome 72.0.3626.74 : **PASSED**
  - Firefox 15.0 (13894) : **PASSED**

**Comment by sobolev-alexey** [comment]
Hi @Core-pl 
many thanks for the overview!
We tried to support as many older browsers as we can, but we are limited by browsers' support for `WebAssembly`
https://caniuse.com/#search=WebAssembly
The overview on the caniuse.com site is pretty much in line with the browsers that you listed above.
Internet Explorer (any version) does not support WebAssembly, same as Edge browser below version 16.

**Comment by sobolev-alexey** [comment]
As for the `mam.web.js`, it was part of several releases, but caused issues with code minification tools, so I removed it. 
If we see multiple requests from the community to add a pre-compiled version of `mam.web.js`, we will look into issues and release a patched version later.
