### ISSUE TITLE
Failed to compile when importing mam.client.js in a React Application

### ISSUE THREAD

**Issue by allemanfredi** [iotaledger-archive/mam.client.js#31]
I'm writing a React application that uses the mam protocol in order to send and receive message and  i'm following your guide about the process of importing mam.client.js file, but when i build the application i receive the following error:

>Failed to compile.
./src/mam/lib/mam.client.js
  Line 4:      'define' is not defined                 no-undef
  Line 5:      'define' is not defined                 no-undef
  Line 142:    Unexpected use of 'self'                no-restricted-globals
  Line 142:    Unexpected use of 'self'                no-restricted-globals
  Line 142:    Unexpected use of 'self'                no-restricted-globals
  Line 157:    'define' is not defined                 no-undef
  Line 159:    'define' is not defined                 no-undef
  Line 1217:   Unexpected use of 'self'                no-restricted-globals
  Line 1217:   Unexpected use of 'self'                no-restricted-globals
  Line 1577:   'chrome' is not defined                 no-undef
  Line 1578:   'chrome' is not defined                 no-undef
  Line 1827:   'define' is not defined                 no-undef
  Line 1829:   'define' is not defined                 no-undef
  Line 4485:   'define' is not defined                 no-undef
  Line 4487:   'define' is not defined                 no-undef
  Line 4689:   'define' is not defined                 no-undef
  Line 4691:   'define' is not defined                 no-undef
  Line 4829:   'define' is not defined                 no-undef
  Line 4831:   'define' is not defined                 no-undef
  Line 5640:   'define' is not defined                 no-undef
  Line 5642:   'define' is not defined                 no-undef
  Line 7011:   'define' is not defined                 no-undef
  Line 7013:   'define' is not defined                 no-undef
  Line 7166:   'define' is not defined                 no-undef
  Line 7168:   'define' is not defined                 no-undef
  Line 9004:   'define' is not defined                 no-undef
  Line 9006:   'define' is not defined                 no-undef
  Line 9208:   'define' is not defined                 no-undef
  Line 9210:   'define' is not defined                 no-undef
  Line 10193:  'read' is not defined                   no-undef
  Line 10199:  'readbuffer' is not defined             no-undef
  Line 10200:  'read' is not defined                   no-undef
  Line 10202:  'scriptArgs' is not defined             no-undef
  Line 10207:  'quit' is not defined                   no-undef
  Line 10242:  Unexpected use of 'print'               no-restricted-globals
  Line 10242:  Unexpected use of 'print'               no-restricted-globals
  Line 10242:  'printErr' is not defined               no-undef
  Line 10325:  'tempI64' is not defined                no-undef
  Line 10325:  'tempDouble' is not defined             no-undef
  Line 10325:  'tempDouble' is not defined             no-undef
  Line 10325:  'tempDouble' is not defined             no-undef
  Line 10325:  'tempDouble' is not defined             no-undef
  Line 10325:  'tempDouble' is not defined             no-undef
  Line 10325:  'tempDouble' is not defined             no-undef
  Line 10325:  'tempI64' is not defined                no-undef
  Line 10325:  'tempI64' is not defined                no-undef
  Line 10567:  'emscripten_source_map' is not defined  no-undef
  Line 10608:  '___cxa_free_exception' is not defined  no-undef
  Line 10759:  'readline' is not defined               no-undef
  Line 11245:  'FileReaderSync' is not defined         no-undef
  Line 11834:  'path' is not defined                   no-undef
  Line 12099:  'Browser' is not defined                no-undef
  Line 12112:  'Browser' is not defined                no-undef
  Line 12215:  'SOCKFS' is not defined                 no-undef
  Line 12218:  '__read_sockaddr' is not defined        no-undef
  Line 12218:  'DNS' is not defined                    no-undef
  Line 23707:  'regeneratorRuntime' is not defined     no-undef
  Line 23712:  'regeneratorRuntime' is not defined     no-undef
  Line 23862:  'regeneratorRuntime' is not defined     no-undef
  Line 23867:  'regeneratorRuntime' is not defined     no-undef
  Line 23970:  'regeneratorRuntime' is not defined     no-undef
  Line 23972:  'regeneratorRuntime' is not defined     no-undef
  Line 23996:  'regeneratorRuntime' is not defined     no-undef
  Line 23999:  'regeneratorRuntime' is not defined     no-undef
  Line 24054:  'regeneratorRuntime' is not defined     no-undef
  Line 24060:  'regeneratorRuntime' is not defined     no-undef
  Line 29419:  Unexpected use of 'self'                no-restricted-globals
  Line 29419:  Unexpected use of 'self'                no-restricted-globals
  Line 35935:  'define' is not defined                 no-undef
  Line 35937:  'define' is not defined                 no-undef
  Line 35958:  'define' is not defined                 no-undef
  Line 35960:  'define' is not defined                 no-undef
  Line 36039:  'define' is not defined                 no-undef
  Line 36041:  'define' is not defined                 no-undef
  Line 36193:  'define' is not defined                 no-undef
  Line 36195:  'define' is not defined                 no-undef
  Line 36278:  'define' is not defined                 no-undef
  Line 36280:  'define' is not defined                 no-undef
  Line 36366:  'define' is not defined                 no-undef
  Line 36368:  'define' is not defined                 no-undef
  Line 36694:  'define' is not defined                 no-undef
  Line 36696:  'define' is not defined                 no-undef
  Line 36966:  'define' is not defined                 no-undef
  Line 36968:  'define' is not defined                 no-undef
  Line 37116:  'define' is not defined                 no-undef
  Line 37118:  'define' is not defined                 no-undef
  Line 37199:  'define' is not defined                 no-undef
  Line 37201:  'define' is not defined                 no-undef
  Line 37262:  'define' is not defined                 no-undef
  Line 37264:  'define' is not defined                 no-undef
  Line 37383:  'define' is not defined                 no-undef
  Line 37385:  'define' is not defined                 no-undef
  Line 37442:  'define' is not defined                 no-undef
  Line 37444:  'define' is not defined                 no-undef
  Line 37487:  'define' is not defined                 no-undef
  Line 37489:  'define' is not defined                 no-undef
  Line 37541:  'define' is not defined                 no-undef
  Line 37543:  'define' is not defined                 no-undef
  Line 37590:  'define' is not defined                 no-undef
  Line 37592:  'define' is not defined                 no-undef
  Line 37635:  'define' is not defined                 no-undef
  Line 37637:  'define' is not defined                 no-undef
  Line 37685:  'define' is not defined                 no-undef
  Line 37687:  'define' is not defined                 no-undef
  Line 37720:  'define' is not defined                 no-undef
  Line 37722:  'define' is not defined                 no-undef
  Line 37791:  'define' is not defined                 no-undef
  Line 37793:  'define' is not defined                 no-undef
  Line 38028:  'define' is not defined                 no-undef
  Line 38030:  'define' is not defined                 no-undef
  Line 38803:  'define' is not defined                 no-undef
  Line 38805:  'define' is not defined                 no-undef
  Line 38947:  'define' is not defined                 no-undef
  Line 38949:  'define' is not defined                 no-undef
  Line 39144:  'define' is not defined                 no-undef
  Line 39146:  'define' is not defined                 no-undef

**Comment by sobolev-alexey** [comment]
@allemanfredi have you used the unofficial version from NPM and installed it via `npm install mam.client`?
How the `mam.client.js` dependency in your `package.json` file looks like?

It should be declared as `"mam.client.js": "iotaledger/mam.client.js",` or installed from NPM as `npm install @iota/mam`
and then imported into your React application as `import Mam from 'mam.client.js';` or `import Mam from '@iota/mam';`

**Comment by allemanfredi** [comment]
@sobolev-alexey Thank you for your help but following your instructions i receive the following error during the build:

`Failed to minify the code from this file:  ./node_modules/@iota/mam/lib/mam.client.js:10128`

Fo buiding my application i use this command:
`react-scripts build`

**Comment by sobolev-alexey** [comment]
Hi @allemanfredi 
could you please provide content of your project configuration files (if any), especially `.babelrc`, `webpack.config.js` and `dependencies/devDependencies` part of the `package.json` file.

I'm trying to reproduce this issue, with my test configuration (`create-react-app v2.1.3` and `react-scripts v2.1.3`) it works fine

**Comment by sobolev-alexey** [comment]
I released a new version of the library which includes a few fixes for the fetch functionality. 
It is not yet available for install over `@iota/mam`, but you can install it by adding the following dependency to your `package.json`: `"mam.client.js": "iotaledger/mam.client.js",`

**Comment by sobolev-alexey** [comment]
In some cases production build with `react-scripts` can fail. In these cases I would suggest to disable source map generation. You can do this by modifying the script line in your `package.json`
```
"scripts": {
    "build": "export GENERATE_SOURCEMAP=false && react-scripts build"
},
```

**Comment by allemanfredi** [comment]
Hi @sobolev-alexey, 
I had an old version of `react-script` (1.2.5). Now, by updating the version it seems to work.

I performed the build with `react-scripts build`. As soon as i test, i will give you a feedback.

Thank you very much!!

**Comment by allemanfredi** [comment]
@sobolev-alexey it seem to work however if use chrome i receive this error:
`mam.client.js:13362 thread '<unnamed>' panicked at 'called Option::unwrap() on a None value', libcore/option.rs:335:21`
`mam.client.js:13362 note: Run with `RUST_BACKTRACE=1` for a backtrace`
`failed to parse:  5273168`.

However i can seed the fetched data.

**Comment by allemanfredi** [comment]
Is it normal that fetch return `undefined`? Or should i see `next_root` ?

**Comment by allemanfredi** [comment]
now, by updating `mam.client.js` i receive the following error:

`Uncaught (in promise) CompileError: WebAssembly Instantiation: Wasm code generation disallowed by embedder`

**Comment by allemanfredi** [comment]
It seems to work but during the fetch i received always 0 `messages`.

`Fetch` return always the same `next_root`.

**Comment by sobolev-alexey** [comment]
@allemanfredi which browser version are you using?

**Comment by sobolev-alexey** [comment]
You can also check your MAM channel with MAM-explorer https://mam-explorer.firebaseapp.com
If it returns 0 messages where you would expect some, please screenshot a QR code from the header and send it to me, I'll take a look

**Comment by allemanfredi** [comment]
i tried to use MAM-explorer but i don't see anything and i received the following error (on the console): 
`MAM.js:36 Uncaught (in promise) undefined`

Instead, the google chrome version i'm using is: `Version 71.0.3578.98`

**Comment by sobolev-alexey** [comment]
> please screenshot a QR code from the header and send it to me, I'll take a look

**Comment by allemanfredi** [comment]
Hey, this is the screenshot:
<img width="103" alt="screenshot 2019-02-08 at 13 40 49" src="https://user-images.githubusercontent.com/29075795/52478927-3af24700-2ba7-11e9-83ce-3e4dec2986dc.png">

I'd like to talk with you in private, is it possible?

**Comment by sobolev-alexey** [comment]
@allemanfredi this is fixed, with the link below you can now fetch your MAM stream
https://mam-explorer.firebaseapp.com/?provider=https://nodes.devnet.thetangle.org:443&mode=public&root=AUEJLPKHDUUKIWCTMALOYQIFGXA9RIRKEGDPCYCIQTYNICLT9ALQGXJFOOXUTKUQJAUUZDQCXNEDEUOLG

**Comment by sobolev-alexey** [comment]
For fetching you can use similar functionality 
https://github.com/iotaledger/mam-explorer/blob/master/src/utils/MAM.js

**Comment by allemanfredi** [comment]
Thank you very much!
