### ISSUE TITLE
how to publish message to the nextRoot?

### ISSUE THREAD

**Issue by raymond00000** [iotaledger-archive/mam.client.js#36]
i checked the example. it always "init" to the first root for the same seed.
How to move the first root to the next root and publish msg on it?
Thanks!

**Comment by sobolev-alexey** [comment]
Hi @raymond00000 
you need to keep the state (`mamState`) in a variable and call `MAM.create(mamState, trytes)` for every new MAM event. This call will return an object, from which you can extract and save the next `mamState`
```
  const message = Mam.create(mamState, trytes)
  mamState = message.state
```
Please take a look at the Node.js example file https://github.com/iotaledger/mam.client.js/blob/master/example/publishAndFetch.js

**Comment by raymond00000** [comment]
If I loss the state, is there any quick way to restore it without fetching from beginning? Thanks.

**Comment by sobolev-alexey** [comment]
you need to have `root`, `next_root` and `start` params from your MAM state in order to attach new events.
