### ISSUE TITLE
unable to fetch when more messages added 

### ISSUE THREAD

**Issue by raymond00000** [iotaledger-archive/mam.client.js#41]
suppose there were 8 messages. Both the explorer and code failed to retrieve all 8 messages. Thanks. 

https://mam-explorer.firebaseapp.com/?provider=https://nodes.devnet.iota.org&mode=restricted&key=VERYSECRETKEY99999999999999999999999999999999999999999999999999999999999999999999&root=JGAFVBCBXMALIJHRVGCGNF9DKBOHSJDPWWIYCNPWYNX9QKYENLKLOFBKMIENYTWXJVMMQZLSTPMEIFXJP

let froot =  'JGAFVBCBXMALIJHRVGCGNF9DKBOHSJDPWWIYCNPWYNX9QKYENLKLOFBKMIENYTWXJVMMQZLSTPMEIFXJP'
const execute = async () => {
  var resp = await Mam.fetch(froot, mode, secretKey, logData)
  console.log(resp)
}
execute()

Fetched and parsed { message: 'Message from Alice',
  timestamp: '2019-2-8 17:46:29' } 

Fetched and parsed { message: 'Message from Bob', timestamp: '2019-2-8 17:46:54' } 

Fetched and parsed { message: 'Message from Charlie',
  timestamp: '2019-2-8 17:46:59' } 

Fetched and parsed { message: 'Message from Alice',
  timestamp: '2019-2-8 17:48:37' } 

Fetched and parsed { message: 'Message from Bob', timestamp: '2019-2-8 17:49:02' } 

Fetched and parsed { message: 'Message from Charlie',
  timestamp: '2019-2-8 17:49:07' } 

Fetched and parsed { message: 'Message from Alice',
  timestamp: '2019-2-8 17:59:44' } 

Fetched and parsed { message: 'Message from Bob', timestamp: '2019-2-8 18:00:09' } 

failed to parse:  { FetchError: invalid json response body at https://nodes.devnet.iota.org/ reason: Unexpected end of JSON input
    at /home/lscm/iota-example/new_mem/mam.client.js/lib/mam.client.js:44172:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  message: 'invalid json response body at https://nodes.devnet.iota.org/ reason: Unexpected end of JSON input',
  type: 'invalid-json' }
undefined

**Comment by sobolev-alexey** [comment]
Yes,. I'm aware about this issue, it is the `https://nodes.devnet.iota.org` provider that is undergoing maintenance and is currently unstable. 
Please change to another provider like `https://nodes.devnet.thetangle.org:443` or `https://testnet140.tangle.works`

**Comment by raymond00000** [comment]
yes, right, turned out was the node's issue. thanks.
