### ISSUE TITLE
MAM.fetch exception

### ISSUE THREAD

**Issue by simonpfeifhofer** [iotaledger-archive/mam.client.js#5]
I get the following error calling MAM.fetch():

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
mam.node.js:9459
note: Run with `RUST_BACKTRACE=1` for a backtrace.
mam.node.js:9459
failed to parse:  5275944

**Comment by simonpfeifhofer** [comment]
Steps to reproduce: 

Start three processes:
1) Start public MAM-stream 1
2) Start public MAM-stream 2
3) Start fetching MAM-stream 1 or 2

For 1) and 2): 
Call MAM.init() with the same seed. Publish the same messages.

For 3)
Fetch for a (duplicate) root from MAM-stream 1 (and 2).

IMO the error is fine, but the message is confusing. Maybe it's possible to give a hint which helps to detect the root-cause of the problem.

**Comment by sdellava** [comment]
Same problem here.

**Comment by sobolev-alexey** [comment]
This is fixed in version `0.1.1`
