### ISSUE TITLE
Where is the source for '../lib/mam'?

### ISSUE THREAD

**Issue by CraigglesO** [iotaledger-archive/mam.client.js#54]
`const { createContext, Reader, Mode } = require('../lib/mam')`

This is in index, but where is the source? I would like to review it.

Thanks,
Craig.

**Comment by obany** [comment]
You can find it in this branch https://github.com/iotaledger/mam.client.js/tree/next/wasm it is essentially a wrapper around entangled.

**Comment by CraigglesO** [comment]
I see thanks.
