### ISSUE TITLE
Request error: Couldn't get a response from nodes

### ISSUE THREAD

**Issue by lucianosilvi** [iotaledger-archive/mam.client.js#70]
Hello,
I'm getting the error message `Request error: Couldn't get a response from nodes` when trying to publish a message. It was working until some days ago, and nothing has changed in the code. 
I'm connecting to the provider with URL https://nodes.thetangle.org:443 

What could be happening?

Thanks

**Comment by obany** [comment]
It could be that the nodes were offline, they are community run nodes. You could try the following nodes as an alternative `https://nodes.iota.org:443/`

**Comment by lucianosilvi** [comment]
> It could be that the nodes were offline, they are community run nodes. You could try the following nodes as an alternative `https://nodes.iota.org:443/`

Thanks @obany , now using that node I get 
`"Request error: must deposit at least 1000000 tokens via the output transaction: invalid migration bundle"`

Has something changed making this MAM library outdated or something like that?

**Comment by obany** [comment]
The legacy mainnet is now deprecated, looks like it doesn't even allow data transactions, I wasn't aware that was the case.
If you want to continue testing with a legacy network you will have to use the legacy devnet `https://nodes.devnet.iota.org:443`

But you should probably move to the new chrysalis network, if you update to the latest mam.js v1.5.0  you can use `https://chrysalis-nodes.iota.org`

**Comment by lucianosilvi** [comment]
Great, I'll use the latest MAM then.
Thank you!
